author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2020-03-13
description = Stack list of series
tags = C53
min-version = 2019b
data-requirement = needs-time-series-data
public = stack_data
help = stack.txt
sample-script = stack_sample.inp
