author = Artur Tarassow
email = atecon@posteo.de
version = 1.1
date = 2024-09-06
description = Stack and unstack data
tags = C81
min-version = 2020c
public = stack_data stack_matdata unstack
help = stack_data_help.md
sample-script = stack_data_sample.inp
data-files = international_gdp.gdt
