author = Artur Tarassow
email = atecon@posteo.de
version = 1.0
date = 2021-03-05
description = Stack list of series
tags = C81
min-version = 2020b
public = stack_data stack_matdata unstack
help = stack_data_help.txt
sample-script = stack_data_sample.inp
data-files = international_gdp.gdt
