author = Artur Tarassow
email = atecon@posteo.de
version = 0.9
date = 2020-03-24
description = Stack list of series
tags = C81
min-version = 2019b
public = stack_data
help = stack_data_help.txt
sample-script = stack_data_sample.inp
